version: "3.3"

services:
        mysql:
                restart: always
                image: mysql:5.7
                container_name: mysql
                command: --init-file /data/application/init.sql
                environment:
                  - MYSQL_ROOT_USER=root
                  - MYSQL_ROOT_PASSWORD=nOtSeCuRe
                  - MYSQL_DATABASE=pms
                volumes:
                        - ./init.sql:/data/application/init.sql
                        - ./mysql-data:/var/lib/mysql
                ports:
                        - "3306:3306"
        nginx:
                build: ./nginx
                container_name: nginx
                restart: always
                ports:
                        - "80:80"
        flask:
                environment:
                  - FLASK_CONFIG=development
                  - FLASK_APP=run.py
                  - MYSQL_HOST=db
                  - MYSQL_DATABASE=pms
                container_name: flask
                restart: always
                depends_on:
                        - mysql
                links:
                        - mysql:db
                expose:
                        - 8080
                build: ./flask
